# Common HelmRelease values
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#	Kubernetes namespace in kustomization.yaml
namespace: apps

resources:
  - ../../../apps/actualbudget/overlays/prod
  - ../../../apps/bentopdf/overlays/prod
  - ../../../apps/carlogger/overlays/prod
  - ../../../apps/deemix/overlays/prod
  - ../../../apps/excalidraw/overlays/prod
  - ../../../apps/gaseous/overlays/prod
  - ../../../apps/homepage/overlays/prod
  - ../../../apps/jellyfin/overlays/prod
  - ../../../apps/metube/overlays/prod
  - ../../../apps/music-assistant/overlays/prod
  - ../../../apps/omni-tools/overlays/prod
  - ../../../apps/paperless-ngx/overlays/prod
  - ../../../apps/speedtest/overlays/prod
  - ../../../apps/uptime/overlays/prod
  - ../../../apps/karakeep/overlays/prod

patches:
  - target:
      kind: HelmRelease
    path: common-patch.yaml
